// AUTO-GENERATED by scripts/build-manifest.mjs — do not edit by hand.
// Run: npm run manifest:build

export interface ManifestEntry {
  path: string;
  vendor: string;
  category: string;
  kind: "db" | "theory";
  productCount: number;
  name: string;
  manufacturer: string;
  currency: string;
}

export interface SystemEntry {
  id: number;
  vendor: string;
  category: string;
  manufacturer: string;
  currency: string;
  dbPath: string;
  theoryPath: string | null;
  productCount: number;
  name: string;
}

export const MANIFEST: ManifestEntry[] = [
  {
    "path": "DATABASE/ARUBA/aruba_db.json",
    "vendor": "ARUBA",
    "category": "",
    "kind": "db",
    "productCount": 13,
    "name": "HPE Aruba Instant On Database",
    "manufacturer": "HPE Aruba (Hewlett Packard Enterprise)",
    "currency": "USD"
  },
  {
    "path": "DATABASE/ARUBA/aruba_selection_theory.json",
    "vendor": "ARUBA",
    "category": "",
    "kind": "theory",
    "productCount": 0,
    "name": "HPE Aruba Instant On Selection Theory",
    "manufacturer": "HPE Aruba",
    "currency": "USD"
  },
  {
    "path": "DATABASE/Cables/cables_general_db.json",
    "vendor": "Cables",
    "category": "",
    "kind": "db",
    "productCount": 138,
    "name": "General Cables Database — Coaxial, UTP, HDMI, VGA, USB, Audio, Power, Fiber HDMI",
    "manufacturer": "Cables",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/Accessories/dsppa_accessories_db.json",
    "vendor": "DSPPA",
    "category": "Accessories",
    "kind": "db",
    "productCount": 22,
    "name": "DSPPA Accessories & Wall Plates Database",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/AMPLIFIERS/dsppa_amplifiers_db.json",
    "vendor": "DSPPA",
    "category": "AMPLIFIERS",
    "kind": "db",
    "productCount": 137,
    "name": "DSPPA Amplifier Database",
    "manufacturer": "DSPPA (Guangzhou DSPPA Audio Co., Ltd.)",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/AMPLIFIERS/dsppa_amplifier_selection_theory.json",
    "vendor": "DSPPA",
    "category": "AMPLIFIERS",
    "kind": "theory",
    "productCount": 0,
    "name": "DSPPA Amplifier Selection Theory — Standards Based",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/Conference/dsppa_conference_db.json",
    "vendor": "DSPPA",
    "category": "Conference",
    "kind": "db",
    "productCount": 47,
    "name": "DSPPA Conference System Database",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/Conference/dsppa_conference_selection_theory.json",
    "vendor": "DSPPA",
    "category": "Conference",
    "kind": "theory",
    "productCount": 0,
    "name": "DSPPA Conference Selection Theory",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/IP NETWORK SELUTION/dsppa_ip_network_db.json",
    "vendor": "DSPPA",
    "category": "IP NETWORK SELUTION",
    "kind": "db",
    "productCount": 22,
    "name": "DSPPA IP Network PA & Accessories Database",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/IP NETWORK SELUTION/dsppa_ip_network_selection_theory.json",
    "vendor": "DSPPA",
    "category": "IP NETWORK SELUTION",
    "kind": "theory",
    "productCount": 0,
    "name": "DSPPA IP Network PA Selection Theory",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/MATRIX/dsppa_matrix_db.json",
    "vendor": "DSPPA",
    "category": "MATRIX",
    "kind": "db",
    "productCount": 7,
    "name": "DSPPA Matrix System Database",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/MATRIX/dsppa_matrix_selection_theory.json",
    "vendor": "DSPPA",
    "category": "MATRIX",
    "kind": "theory",
    "productCount": 0,
    "name": "DSPPA Matrix Selection Theory",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/misc/dsppa_misc_zero_price_db.json",
    "vendor": "DSPPA",
    "category": "misc",
    "kind": "db",
    "productCount": 66,
    "name": "DSPPA Miscellaneous & Zero-Price Items Database",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/PAVA/dsppa_pava_db.json",
    "vendor": "DSPPA",
    "category": "PAVA",
    "kind": "db",
    "productCount": 9,
    "name": "DSPPA PAVA EN54 Voice Evacuation Database",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/PAVA/dsppa_pava_selection_theory.json",
    "vendor": "DSPPA",
    "category": "PAVA",
    "kind": "theory",
    "productCount": 0,
    "name": "DSPPA PAVA EN54 Selection Theory",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/SPEAKERS/dsppa_speakers_db.json",
    "vendor": "DSPPA",
    "category": "SPEAKERS",
    "kind": "db",
    "productCount": 169,
    "name": "DSPPA Speaker Database",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/DSPPA/SPEAKERS/dsppa_speaker_selection_theory.json",
    "vendor": "DSPPA",
    "category": "SPEAKERS",
    "kind": "theory",
    "productCount": 0,
    "name": "DSPPA Speaker Selection Theory — Standards Based",
    "manufacturer": "DSPPA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/ESVIZ/ezviz_db.json",
    "vendor": "ESVIZ",
    "category": "",
    "kind": "db",
    "productCount": 64,
    "name": "EZVIZ Smart Home Security Database",
    "manufacturer": "EZVIZ (Hikvision Consumer Brand)",
    "currency": "USD"
  },
  {
    "path": "DATABASE/ESVIZ/ezviz_retail_db.json",
    "vendor": "ESVIZ",
    "category": "",
    "kind": "db",
    "productCount": 94,
    "name": "EZVIZ Consumer Product Database (Retail Edition)",
    "manufacturer": "EZVIZ (Hikvision Consumer Brand)",
    "currency": "USD"
  },
  {
    "path": "DATABASE/ESVIZ/ezviz_selection_theory.json",
    "vendor": "ESVIZ",
    "category": "",
    "kind": "theory",
    "productCount": 0,
    "name": "EZVIZ Smart Home Selection Theory",
    "manufacturer": "EZVIZ",
    "currency": "USD"
  },
  {
    "path": "DATABASE/Extreme cabinet/expert_cabinets_db.json",
    "vendor": "Extreme cabinet",
    "category": "",
    "kind": "db",
    "productCount": 62,
    "name": "Expert/EX Network Cabinet & Rack Infrastructure Database",
    "manufacturer": "Expert (EX Series)",
    "currency": "JOD (Jordanian Dinar)"
  },
  {
    "path": "DATABASE/Extreme cabinet/expert_cabinets_selection_theory.json",
    "vendor": "Extreme cabinet",
    "category": "",
    "kind": "theory",
    "productCount": 0,
    "name": "Network Cabinet & Rack Selection Theory",
    "manufacturer": "Extreme cabinet",
    "currency": "USD"
  },
  {
    "path": "DATABASE/fanvil/fanvil_db.json",
    "vendor": "fanvil",
    "category": "",
    "kind": "db",
    "productCount": 126,
    "name": "Fanvil IP Communication Products Database",
    "manufacturer": "Fanvil",
    "currency": "USD"
  },
  {
    "path": "DATABASE/fanvil/fanvil_selection_theory.json",
    "vendor": "fanvil",
    "category": "",
    "kind": "theory",
    "productCount": 0,
    "name": "Fanvil IP Communication Selection Theory",
    "manufacturer": "Fanvil",
    "currency": "USD"
  },
  {
    "path": "DATABASE/General Accessories/general_accessories_db.json",
    "vendor": "General Accessories",
    "category": "",
    "kind": "db",
    "productCount": 276,
    "name": "General Accessories, AV Equipment & Consumables Database (Complete)",
    "manufacturer": "General Accessories",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Access control and Time Attendance/hikvision_access_control_db.json",
    "vendor": "HIKVISION",
    "category": "Access control and Time Attendance",
    "kind": "db",
    "productCount": 63,
    "name": "Hikvision Access Control & Time Attendance Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Access control and Time Attendance/access_control_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "Access control and Time Attendance",
    "kind": "theory",
    "productCount": 0,
    "name": "Access Control Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Alarm system/hikvision_alarm_db.json",
    "vendor": "HIKVISION",
    "category": "Alarm system",
    "kind": "db",
    "productCount": 61,
    "name": "Hikvision Alarm System Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Alarm system/alarm_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "Alarm system",
    "kind": "theory",
    "productCount": 0,
    "name": "Alarm System Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Analoge Cameras/hikvision_analog_cameras_db.json",
    "vendor": "HIKVISION",
    "category": "Analoge Cameras",
    "kind": "db",
    "productCount": 61,
    "name": "Hikvision Turbo HD Analog Camera Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Analoge Cameras/analog_camera_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "Analoge Cameras",
    "kind": "theory",
    "productCount": 0,
    "name": "Turbo HD Analog Camera Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Cables/hikvision_cables_db.json",
    "vendor": "HIKVISION",
    "category": "Cables",
    "kind": "db",
    "productCount": 26,
    "name": "Hikvision UTP Cable & Accessories Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Cables/cables_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "Cables",
    "kind": "theory",
    "productCount": 0,
    "name": "UTP Cable & Infrastructure Selection Theory",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/DVR-NVR/hikvision_dvr_nvr_db.json",
    "vendor": "HIKVISION",
    "category": "DVR-NVR",
    "kind": "db",
    "productCount": 117,
    "name": "Hikvision DVR & NVR Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/DVR-NVR/dvr_nvr_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "DVR-NVR",
    "kind": "theory",
    "productCount": 0,
    "name": "DVR & NVR Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Gates Barrier/hikvision_barrier_db.json",
    "vendor": "HIKVISION",
    "category": "Gates Barrier",
    "kind": "db",
    "productCount": 16,
    "name": "Hikvision Gate Barrier System Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Gates Barrier/barrier_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "Gates Barrier",
    "kind": "theory",
    "productCount": 0,
    "name": "Gate Barrier Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/HDD/hikvision_hdd_db.json",
    "vendor": "HIKVISION",
    "category": "HDD",
    "kind": "db",
    "productCount": 13,
    "name": "Surveillance Hard Drive Database",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/HDD/hdd_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "HDD",
    "kind": "theory",
    "productCount": 0,
    "name": "Surveillance HDD Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Interactive Screen/hikvision_interactive_db.json",
    "vendor": "HIKVISION",
    "category": "Interactive Screen",
    "kind": "db",
    "productCount": 17,
    "name": "Hikvision Interactive Display & Digital Signage Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Interactive Screen/interactive_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "Interactive Screen",
    "kind": "theory",
    "productCount": 0,
    "name": "Interactive Display & Digital Signage Selection Theory",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Intercom/hikvision_intercom_db.json",
    "vendor": "HIKVISION",
    "category": "Intercom",
    "kind": "db",
    "productCount": 67,
    "name": "Hikvision Video Intercom System Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Intercom/intercom_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "Intercom",
    "kind": "theory",
    "productCount": 0,
    "name": "Video Intercom Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/IP Cameera/hikvision_ipc_db.json",
    "vendor": "HIKVISION",
    "category": "IP Cameera",
    "kind": "db",
    "productCount": 121,
    "name": "Hikvision IP Camera Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/IP Cameera/ipc_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "IP Cameera",
    "kind": "theory",
    "productCount": 0,
    "name": "IP Camera Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/MIXED/hikvision_mixed_project_db.json",
    "vendor": "HIKVISION",
    "category": "MIXED",
    "kind": "db",
    "productCount": 138,
    "name": "Hikvision Mixed Project Items Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/MIXED/hikvision_project_items_db.json",
    "vendor": "HIKVISION",
    "category": "MIXED",
    "kind": "db",
    "productCount": 62,
    "name": "Hikvision Project Items Database (Approval Required)",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Monitors/hikvision_monitors_db.json",
    "vendor": "HIKVISION",
    "category": "Monitors",
    "kind": "db",
    "productCount": 17,
    "name": "Hikvision Monitors Engineering Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Monitors/monitor_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "Monitors",
    "kind": "theory",
    "productCount": 0,
    "name": "Monitor Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/PTZ/hikvision_ptz_db.json",
    "vendor": "HIKVISION",
    "category": "PTZ",
    "kind": "db",
    "productCount": 11,
    "name": "Hikvision PTZ Camera Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/PTZ/ptz_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "PTZ",
    "kind": "theory",
    "productCount": 0,
    "name": "PTZ Camera Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Switches/hikvision_switches_db.json",
    "vendor": "HIKVISION",
    "category": "Switches",
    "kind": "db",
    "productCount": 42,
    "name": "Hikvision Network Switches Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Switches/switches_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "Switches",
    "kind": "theory",
    "productCount": 0,
    "name": "Network Switch Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Turnstile/hikvision_turnstile_db.json",
    "vendor": "HIKVISION",
    "category": "Turnstile",
    "kind": "db",
    "productCount": 6,
    "name": "Hikvision Turnstile & Gate Opener Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Turnstile/turnstile_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "Turnstile",
    "kind": "theory",
    "productCount": 0,
    "name": "Turnstile & Gate Opener Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Video wall/hikvision_videowall_db.json",
    "vendor": "HIKVISION",
    "category": "Video wall",
    "kind": "db",
    "productCount": 11,
    "name": "Hikvision Video Wall System Database",
    "manufacturer": "Hikvision",
    "currency": "USD"
  },
  {
    "path": "DATABASE/HIKVISION/Video wall/videowall_selection_theory.json",
    "vendor": "HIKVISION",
    "category": "Video wall",
    "kind": "theory",
    "productCount": 0,
    "name": "Video Wall Selection Theory - Standards Based",
    "manufacturer": "HIKVISION",
    "currency": "USD"
  },
  {
    "path": "DATABASE/LEGREND/legrand_db.json",
    "vendor": "LEGREND",
    "category": "",
    "kind": "db",
    "productCount": 64,
    "name": "Legrand UPS & LCS Structured Cabling Database",
    "manufacturer": "Legrand",
    "currency": "USD"
  },
  {
    "path": "DATABASE/LEGREND/legrand_selection_theory.json",
    "vendor": "LEGREND",
    "category": "",
    "kind": "theory",
    "productCount": 0,
    "name": "Legrand UPS & LCS Cabling Selection Theory",
    "manufacturer": "Legrand",
    "currency": "USD"
  },
  {
    "path": "DATABASE/PLANET/planet_db.json",
    "vendor": "PLANET",
    "category": "",
    "kind": "db",
    "productCount": 60,
    "name": "PLANET Networking & Communication Database",
    "manufacturer": "PLANET Technology Corporation",
    "currency": "USD"
  },
  {
    "path": "DATABASE/PLANET/planet_selection_theory.json",
    "vendor": "PLANET",
    "category": "",
    "kind": "theory",
    "productCount": 0,
    "name": "PLANET Networking Selection Theory",
    "manufacturer": "PLANET",
    "currency": "USD"
  },
  {
    "path": "DATABASE/SCHENIDER/schneider_actassi_db.json",
    "vendor": "SCHENIDER",
    "category": "",
    "kind": "db",
    "productCount": 97,
    "name": "Schneider Electric Actassi Structured Cabling & Infrastructure Database",
    "manufacturer": "Schneider Electric",
    "currency": "USD"
  },
  {
    "path": "DATABASE/SCHENIDER/schneider_actassi_selection_theory.json",
    "vendor": "SCHENIDER",
    "category": "",
    "kind": "theory",
    "productCount": 0,
    "name": "Schneider Electric Actassi Structured Cabling Selection Theory",
    "manufacturer": "Schneider Electric",
    "currency": "USD"
  },
  {
    "path": "DATABASE/SIB/sib_access_db.json",
    "vendor": "SIB",
    "category": "",
    "kind": "db",
    "productCount": 98,
    "name": "SIB Access Control Hardware Database",
    "manufacturer": "SIB (Generic/OEM Access Control Hardware)",
    "currency": "USD"
  },
  {
    "path": "DATABASE/SIB/sib_access_selection_theory.json",
    "vendor": "SIB",
    "category": "",
    "kind": "theory",
    "productCount": 0,
    "name": "SIB Standalone Access Control Selection Theory",
    "manufacturer": "SIB",
    "currency": "USD"
  },
  {
    "path": "DATABASE/TENDA/tenda_networking_db.json",
    "vendor": "TENDA",
    "category": "",
    "kind": "db",
    "productCount": 76,
    "name": "Tenda Networking Products Database",
    "manufacturer": "TENDA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/TENDA/tenda_networking_selection_theory.json",
    "vendor": "TENDA",
    "category": "",
    "kind": "theory",
    "productCount": 0,
    "name": "Tenda & HPE Aruba Networking Selection Theory",
    "manufacturer": "TENDA",
    "currency": "USD"
  },
  {
    "path": "DATABASE/Yeastar/yeastar_db.json",
    "vendor": "Yeastar",
    "category": "",
    "kind": "db",
    "productCount": 9,
    "name": "Yeastar IP PBX & Gateway Database",
    "manufacturer": "Yeastar",
    "currency": "USD"
  },
  {
    "path": "DATABASE/Yeastar/yeastar_selection_theory.json",
    "vendor": "Yeastar",
    "category": "",
    "kind": "theory",
    "productCount": 0,
    "name": "Yeastar IP PBX Selection Theory",
    "manufacturer": "Yeastar",
    "currency": "USD"
  }
];

export const SYSTEMS: SystemEntry[] = [
  {
    "id": 1,
    "vendor": "ARUBA",
    "category": "ARUBA",
    "manufacturer": "HPE Aruba (Hewlett Packard Enterprise)",
    "currency": "USD",
    "dbPath": "DATABASE/ARUBA/aruba_db.json",
    "theoryPath": "DATABASE/ARUBA/aruba_selection_theory.json",
    "productCount": 13,
    "name": "HPE Aruba Instant On Database"
  },
  {
    "id": 2,
    "vendor": "Cables",
    "category": "Cables",
    "manufacturer": "Cables",
    "currency": "USD",
    "dbPath": "DATABASE/Cables/cables_general_db.json",
    "theoryPath": null,
    "productCount": 138,
    "name": "General Cables Database — Coaxial, UTP, HDMI, VGA, USB, Audio, Power, Fiber HDMI"
  },
  {
    "id": 3,
    "vendor": "DSPPA",
    "category": "Accessories",
    "manufacturer": "DSPPA",
    "currency": "USD",
    "dbPath": "DATABASE/DSPPA/Accessories/dsppa_accessories_db.json",
    "theoryPath": null,
    "productCount": 22,
    "name": "DSPPA Accessories & Wall Plates Database"
  },
  {
    "id": 4,
    "vendor": "DSPPA",
    "category": "AMPLIFIERS",
    "manufacturer": "DSPPA (Guangzhou DSPPA Audio Co., Ltd.)",
    "currency": "USD",
    "dbPath": "DATABASE/DSPPA/AMPLIFIERS/dsppa_amplifiers_db.json",
    "theoryPath": "DATABASE/DSPPA/AMPLIFIERS/dsppa_amplifier_selection_theory.json",
    "productCount": 137,
    "name": "DSPPA Amplifier Database"
  },
  {
    "id": 5,
    "vendor": "DSPPA",
    "category": "Conference",
    "manufacturer": "DSPPA",
    "currency": "USD",
    "dbPath": "DATABASE/DSPPA/Conference/dsppa_conference_db.json",
    "theoryPath": "DATABASE/DSPPA/Conference/dsppa_conference_selection_theory.json",
    "productCount": 47,
    "name": "DSPPA Conference System Database"
  },
  {
    "id": 6,
    "vendor": "DSPPA",
    "category": "IP NETWORK SELUTION",
    "manufacturer": "DSPPA",
    "currency": "USD",
    "dbPath": "DATABASE/DSPPA/IP NETWORK SELUTION/dsppa_ip_network_db.json",
    "theoryPath": "DATABASE/DSPPA/IP NETWORK SELUTION/dsppa_ip_network_selection_theory.json",
    "productCount": 22,
    "name": "DSPPA IP Network PA & Accessories Database"
  },
  {
    "id": 7,
    "vendor": "DSPPA",
    "category": "MATRIX",
    "manufacturer": "DSPPA",
    "currency": "USD",
    "dbPath": "DATABASE/DSPPA/MATRIX/dsppa_matrix_db.json",
    "theoryPath": "DATABASE/DSPPA/MATRIX/dsppa_matrix_selection_theory.json",
    "productCount": 7,
    "name": "DSPPA Matrix System Database"
  },
  {
    "id": 8,
    "vendor": "DSPPA",
    "category": "misc",
    "manufacturer": "DSPPA",
    "currency": "USD",
    "dbPath": "DATABASE/DSPPA/misc/dsppa_misc_zero_price_db.json",
    "theoryPath": null,
    "productCount": 66,
    "name": "DSPPA Miscellaneous & Zero-Price Items Database"
  },
  {
    "id": 9,
    "vendor": "DSPPA",
    "category": "PAVA",
    "manufacturer": "DSPPA",
    "currency": "USD",
    "dbPath": "DATABASE/DSPPA/PAVA/dsppa_pava_db.json",
    "theoryPath": "DATABASE/DSPPA/PAVA/dsppa_pava_selection_theory.json",
    "productCount": 9,
    "name": "DSPPA PAVA EN54 Voice Evacuation Database"
  },
  {
    "id": 10,
    "vendor": "DSPPA",
    "category": "SPEAKERS",
    "manufacturer": "DSPPA",
    "currency": "USD",
    "dbPath": "DATABASE/DSPPA/SPEAKERS/dsppa_speakers_db.json",
    "theoryPath": "DATABASE/DSPPA/SPEAKERS/dsppa_speaker_selection_theory.json",
    "productCount": 169,
    "name": "DSPPA Speaker Database"
  },
  {
    "id": 11,
    "vendor": "ESVIZ",
    "category": "ESVIZ",
    "manufacturer": "EZVIZ (Hikvision Consumer Brand)",
    "currency": "USD",
    "dbPath": "DATABASE/ESVIZ/ezviz_retail_db.json",
    "theoryPath": "DATABASE/ESVIZ/ezviz_selection_theory.json",
    "productCount": 94,
    "name": "EZVIZ Consumer Product Database (Retail Edition)"
  },
  {
    "id": 12,
    "vendor": "Extreme cabinet",
    "category": "Extreme cabinet",
    "manufacturer": "Expert (EX Series)",
    "currency": "JOD (Jordanian Dinar)",
    "dbPath": "DATABASE/Extreme cabinet/expert_cabinets_db.json",
    "theoryPath": "DATABASE/Extreme cabinet/expert_cabinets_selection_theory.json",
    "productCount": 62,
    "name": "Expert/EX Network Cabinet & Rack Infrastructure Database"
  },
  {
    "id": 13,
    "vendor": "fanvil",
    "category": "fanvil",
    "manufacturer": "Fanvil",
    "currency": "USD",
    "dbPath": "DATABASE/fanvil/fanvil_db.json",
    "theoryPath": "DATABASE/fanvil/fanvil_selection_theory.json",
    "productCount": 126,
    "name": "Fanvil IP Communication Products Database"
  },
  {
    "id": 14,
    "vendor": "General Accessories",
    "category": "General Accessories",
    "manufacturer": "General Accessories",
    "currency": "USD",
    "dbPath": "DATABASE/General Accessories/general_accessories_db.json",
    "theoryPath": null,
    "productCount": 276,
    "name": "General Accessories, AV Equipment & Consumables Database (Complete)"
  },
  {
    "id": 15,
    "vendor": "HIKVISION",
    "category": "Access control and Time Attendance",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/Access control and Time Attendance/hikvision_access_control_db.json",
    "theoryPath": "DATABASE/HIKVISION/Access control and Time Attendance/access_control_selection_theory.json",
    "productCount": 63,
    "name": "Hikvision Access Control & Time Attendance Database"
  },
  {
    "id": 16,
    "vendor": "HIKVISION",
    "category": "Alarm system",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/Alarm system/hikvision_alarm_db.json",
    "theoryPath": "DATABASE/HIKVISION/Alarm system/alarm_selection_theory.json",
    "productCount": 61,
    "name": "Hikvision Alarm System Database"
  },
  {
    "id": 17,
    "vendor": "HIKVISION",
    "category": "Analoge Cameras",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/Analoge Cameras/hikvision_analog_cameras_db.json",
    "theoryPath": "DATABASE/HIKVISION/Analoge Cameras/analog_camera_selection_theory.json",
    "productCount": 61,
    "name": "Hikvision Turbo HD Analog Camera Database"
  },
  {
    "id": 18,
    "vendor": "HIKVISION",
    "category": "Cables",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/Cables/hikvision_cables_db.json",
    "theoryPath": "DATABASE/HIKVISION/Cables/cables_selection_theory.json",
    "productCount": 26,
    "name": "Hikvision UTP Cable & Accessories Database"
  },
  {
    "id": 19,
    "vendor": "HIKVISION",
    "category": "DVR-NVR",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/DVR-NVR/hikvision_dvr_nvr_db.json",
    "theoryPath": "DATABASE/HIKVISION/DVR-NVR/dvr_nvr_selection_theory.json",
    "productCount": 117,
    "name": "Hikvision DVR & NVR Database"
  },
  {
    "id": 20,
    "vendor": "HIKVISION",
    "category": "Gates Barrier",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/Gates Barrier/hikvision_barrier_db.json",
    "theoryPath": "DATABASE/HIKVISION/Gates Barrier/barrier_selection_theory.json",
    "productCount": 16,
    "name": "Hikvision Gate Barrier System Database"
  },
  {
    "id": 21,
    "vendor": "HIKVISION",
    "category": "HDD",
    "manufacturer": "HIKVISION",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/HDD/hikvision_hdd_db.json",
    "theoryPath": "DATABASE/HIKVISION/HDD/hdd_selection_theory.json",
    "productCount": 13,
    "name": "Surveillance Hard Drive Database"
  },
  {
    "id": 22,
    "vendor": "HIKVISION",
    "category": "Interactive Screen",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/Interactive Screen/hikvision_interactive_db.json",
    "theoryPath": "DATABASE/HIKVISION/Interactive Screen/interactive_selection_theory.json",
    "productCount": 17,
    "name": "Hikvision Interactive Display & Digital Signage Database"
  },
  {
    "id": 23,
    "vendor": "HIKVISION",
    "category": "Intercom",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/Intercom/hikvision_intercom_db.json",
    "theoryPath": "DATABASE/HIKVISION/Intercom/intercom_selection_theory.json",
    "productCount": 67,
    "name": "Hikvision Video Intercom System Database"
  },
  {
    "id": 24,
    "vendor": "HIKVISION",
    "category": "IP Cameera",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/IP Cameera/hikvision_ipc_db.json",
    "theoryPath": "DATABASE/HIKVISION/IP Cameera/ipc_selection_theory.json",
    "productCount": 121,
    "name": "Hikvision IP Camera Database"
  },
  {
    "id": 25,
    "vendor": "HIKVISION",
    "category": "MIXED",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/MIXED/hikvision_project_items_db.json",
    "theoryPath": null,
    "productCount": 62,
    "name": "Hikvision Project Items Database (Approval Required)"
  },
  {
    "id": 26,
    "vendor": "HIKVISION",
    "category": "Monitors",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/Monitors/hikvision_monitors_db.json",
    "theoryPath": "DATABASE/HIKVISION/Monitors/monitor_selection_theory.json",
    "productCount": 17,
    "name": "Hikvision Monitors Engineering Database"
  },
  {
    "id": 27,
    "vendor": "HIKVISION",
    "category": "PTZ",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/PTZ/hikvision_ptz_db.json",
    "theoryPath": "DATABASE/HIKVISION/PTZ/ptz_selection_theory.json",
    "productCount": 11,
    "name": "Hikvision PTZ Camera Database"
  },
  {
    "id": 28,
    "vendor": "HIKVISION",
    "category": "Switches",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/Switches/hikvision_switches_db.json",
    "theoryPath": "DATABASE/HIKVISION/Switches/switches_selection_theory.json",
    "productCount": 42,
    "name": "Hikvision Network Switches Database"
  },
  {
    "id": 29,
    "vendor": "HIKVISION",
    "category": "Turnstile",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/Turnstile/hikvision_turnstile_db.json",
    "theoryPath": "DATABASE/HIKVISION/Turnstile/turnstile_selection_theory.json",
    "productCount": 6,
    "name": "Hikvision Turnstile & Gate Opener Database"
  },
  {
    "id": 30,
    "vendor": "HIKVISION",
    "category": "Video wall",
    "manufacturer": "Hikvision",
    "currency": "USD",
    "dbPath": "DATABASE/HIKVISION/Video wall/hikvision_videowall_db.json",
    "theoryPath": "DATABASE/HIKVISION/Video wall/videowall_selection_theory.json",
    "productCount": 11,
    "name": "Hikvision Video Wall System Database"
  },
  {
    "id": 31,
    "vendor": "LEGREND",
    "category": "LEGREND",
    "manufacturer": "Legrand",
    "currency": "USD",
    "dbPath": "DATABASE/LEGREND/legrand_db.json",
    "theoryPath": "DATABASE/LEGREND/legrand_selection_theory.json",
    "productCount": 64,
    "name": "Legrand UPS & LCS Structured Cabling Database"
  },
  {
    "id": 32,
    "vendor": "PLANET",
    "category": "PLANET",
    "manufacturer": "PLANET Technology Corporation",
    "currency": "USD",
    "dbPath": "DATABASE/PLANET/planet_db.json",
    "theoryPath": "DATABASE/PLANET/planet_selection_theory.json",
    "productCount": 60,
    "name": "PLANET Networking & Communication Database"
  },
  {
    "id": 33,
    "vendor": "SCHENIDER",
    "category": "SCHENIDER",
    "manufacturer": "Schneider Electric",
    "currency": "USD",
    "dbPath": "DATABASE/SCHENIDER/schneider_actassi_db.json",
    "theoryPath": "DATABASE/SCHENIDER/schneider_actassi_selection_theory.json",
    "productCount": 97,
    "name": "Schneider Electric Actassi Structured Cabling & Infrastructure Database"
  },
  {
    "id": 34,
    "vendor": "SIB",
    "category": "SIB",
    "manufacturer": "SIB (Generic/OEM Access Control Hardware)",
    "currency": "USD",
    "dbPath": "DATABASE/SIB/sib_access_db.json",
    "theoryPath": "DATABASE/SIB/sib_access_selection_theory.json",
    "productCount": 98,
    "name": "SIB Access Control Hardware Database"
  },
  {
    "id": 35,
    "vendor": "TENDA",
    "category": "TENDA",
    "manufacturer": "TENDA",
    "currency": "USD",
    "dbPath": "DATABASE/TENDA/tenda_networking_db.json",
    "theoryPath": "DATABASE/TENDA/tenda_networking_selection_theory.json",
    "productCount": 76,
    "name": "Tenda Networking Products Database"
  },
  {
    "id": 36,
    "vendor": "Yeastar",
    "category": "Yeastar",
    "manufacturer": "Yeastar",
    "currency": "USD",
    "dbPath": "DATABASE/Yeastar/yeastar_db.json",
    "theoryPath": "DATABASE/Yeastar/yeastar_selection_theory.json",
    "productCount": 9,
    "name": "Yeastar IP PBX & Gateway Database"
  }
];
