/**
 * Cloudflare Worker entrypoint.
 *
 * Wraps the worker generated by the OpenNext adapter (`.open-next/worker.js`)
 * so we can add a `scheduled()` handler alongside its `fetch()`.
 *
 * Why this file exists
 * ────────────────────
 * On Vercel, the nightly DB backup was driven by `vercel.json → crons`, which
 * issues an HTTP GET to /api/cron/db-backup with an
 * `Authorization: Bearer $CRON_SECRET` header that Vercel injects itself.
 *
 * Cloudflare cron triggers don't make HTTP requests — they invoke the Worker's
 * `scheduled()` export. So we implement `scheduled()` here and have it call the
 * app's existing route through the very same fetch handler, with the same
 * Bearer header the route already knows how to authorise (see
 * `assertAuthorized` in src/app/api/cron/db-backup/route.ts).
 *
 * That means the backup logic itself is untouched and there is exactly one code
 * path for it, whether it's fired by cron or run by hand from the admin UI.
 *
 * NOTE: `./.open-next/worker.js` is build output — it exists only after
 * `npm run cf:build`. Keep this file at the repo root so the relative imports
 * *inside* the generated worker still resolve (esbuild resolves those relative
 * to the generated file, not to this importer).
 */
// eslint-disable-next-line import/no-unresolved -- generated by `npm run cf:build`
import openNextWorker from "./.open-next/worker.js";

/** Path of the daily backup route, matching wrangler.toml's cron schedule. */
const CRON_PATH = "/api/cron/db-backup";

export default {
  fetch(request, env, ctx) {
    return openNextWorker.fetch(request, env, ctx);
  },

  async scheduled(event, env, ctx) {
    const secret = env.CRON_SECRET;
    if (!secret) {
      // Fail loudly in the Worker log rather than silently skipping backups.
      console.error(
        "[cron] CRON_SECRET is not set — skipping the nightly DB backup. " +
          "Set it with: wrangler secret put CRON_SECRET",
      );
      return;
    }

    // The origin is cosmetic (we invoke the handler directly rather than going
    // over the network), but it must be a valid absolute URL because the Next
    // router parses `request.url`. APP_ORIGIN keeps logs/self-links accurate.
    const origin = env.APP_ORIGIN || "https://magictech.local";
    const req = new Request(`${origin}${CRON_PATH}`, {
      method: "GET",
      headers: { Authorization: `Bearer ${secret}` },
    });

    const run = (async () => {
      try {
        const res = await openNextWorker.fetch(req, env, ctx);
        const body = await res.text();
        if (!res.ok) {
          console.error(
            `[cron] db-backup failed: HTTP ${res.status} ${body.slice(0, 500)}`,
          );
          return;
        }
        console.log(`[cron] db-backup ok: ${body.slice(0, 500)}`);
      } catch (err) {
        console.error(
          `[cron] db-backup threw: ${err instanceof Error ? err.message : String(err)}`,
        );
      }
    })();

    // Keep the Worker alive until the backup finishes — cron invocations are
    // terminated as soon as the handler returns otherwise.
    ctx.waitUntil(run);
    await run;
  },
};
